import { Inter } from 'next/font/google'
import './globals.css'
import { StateContextProvider } from '@/Context/NFTs'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Web3 Document MarketPlace',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StateContextProvider>
                  <Toaster 
            position="top-center"
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff',
              },
            }}
          />
        {children}
    </StateContextProvider>
      </body>
    </html>
  )
}
